# Generated by Django 3.0.3 on 2020-03-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200227_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. A culpa et explicabo natus odit quod repellendus saepe. Ab autem corporis deleniti dolore ducimus expedita, impedit, labore recusandae rerum saepe veniam? Amet dicta distinctio earum esse est iure maiores neque nesciunt nulla omnis optio quaerat quis, rerum, sapiente, similique temporibus velit voluptate voluptatem. Consectetur consequuntur corporis natus nulla qui quos, ullam!'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default='04.03.2020 12:23'),
        ),
    ]
